### PR TITLE
Fix ruby version problem

### PR DESCRIPTION
**Pull request by naoufalelh**
# PR Description

✨ This PR fixes the issue number: #40 

✨ Here's the summary of my changes and my motivation behind them:

- changed ruby version in `Gemfile`, `Gemfile.lock` and in `.ruby-version` to `2.7.1`
- changed bundler version to `2.1.4`
- improved a line in documentation with the right commande to change current version inside the project folder only using `rbenv local` instead of `rbenv global`

✨ This PR changes or adds functionality which will require updating the documentation: YES (leave what's relevant)

# Self-check:

Please check all that apply:

- [x] My code follows the style guidelines of this project
- [x] I have reviewed my code, refactored it to the best of my abilities and deleted all unnecessary code
- [x] I have commented my code, particularly in hard-to-understand areas; my comments are concise
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings and no new bugs

✨ ✨ ✨  Thank you for contributing to the Code Bending Dictionary ✨ ✨ ✨

### CODE REVIEW

**Comment by naoufalelh** [comment]
@sylwiavargas can you approve and add label `hacktoberfest-accepted` 

For info : "Your pull requests will count toward your participation if they are in a repository with the hacktoberfest topic and once they have been merged, approved by a maintainer or labelled as `hacktoberfest-accepted`."

**Comment by sylwiavargas** [comment]
Hi @naoufalelh, I'm sorry you had to wait so long. We had an unforeseeable situation. Thank you for your contribution, I have just merged it and added the label!

**Comment by sylwiavargas** [comment]
one more thing, @naoufalelh — would you like to be added to our contributors list in the READme?
If so:
1. Would you give me please your name or nickname you wish to be featured
2. We usually link the github pic — is that ok?

**Comment by naoufalelh** [comment]
@sylwiavargas  yes that would be nice.

1. Naoufal El Hassnaoui
2. the pic from my github profile is ok.

Thanks

**Pull request merged**
