### PR TITLE
Relatedwords dev

### LINKED ISSUE #30: Add RelatedWord
**CREATE:**
- new migration to add a RelatedWords table with the attributes specified below
- a RelatedWord model with appropriate associations
- a RelatedWord Controller with the following actions: new, create, edit, update, destroy
ERD

**UPDATE:**
- seeds file by adding a few RelatedWord instances
- routes file by adding appropriate routes
- Word model with appropriate associations

### PR DESCRIPTION
**Pull request by HyeokJungKim**
# PR Description

✨ This PR fixes the issue number: #30 

✨ Here's the summary of my changes and my motivation behind them:

- Adds the RelatedWord model, so words can be associated with one another
- Related words are bi-directional, so word A being related to word B means that word B is related to word A, meaning that I needed to make sure that the associations work both ways
- Added validations so words can only be related once
- When a word is deleted, all their associations are also deleted

✨ This PR changes or adds functionality which will require updating the documentation: NO 
Documentation on Self-Referentials:
https://collectiveidea.com/blog/archives/2015/07/30/bi-directional-and-self-referential-associations-in-rails
https://guides.rubyonrails.org/association_basics.html#detailed-association-reference

# Self-check:

Please check all that apply:

- [x] My code follows the style guidelines of this project
- [x] I have reviewed my code, refactored it to the best of my abilities and deleted all unnecessary code
- [x] I have commented my code, particularly in hard-to-understand areas; my comments are concise
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings and no new bugs

✨ ✨ ✨  Thank you for contributing to the Code Bending Dictionary ✨ ✨ ✨

### CODE REVIEW

**Review by sylwiavargas — APPROVED** [review]
Hi @HyeokJungKim ! Thank you for your thorough and well-documented changes. ✨

**Review by bigfishh — COMMENTED** [review]
thank you @HyeokJungKim for this contribution and linking the resources used! 

just one thing, could you double-check the validations? when the following snippet of code is placed in the seeds file -- they are still getting created: 

```ruby 
RelatedWord.create(word_one: Word.second, word_two: Word.first)
RelatedWord.create(word_one: Word.first, word_two: Word.second)
RelatedWord.create(word_one: Word.first, word_two: Word.first)
RelatedWord.create(word_one: Word.second, word_two: Word.second)
```

**Comment by HyeokJungKim** [comment]
@bigfishh 
Oh good call - I'll add validations so a word can't be associated with itself.

```
RelatedWord.create(word_one: Word.second, word_two: Word.first)
RelatedWord.create(word_one: Word.first, word_two: Word.second)
```

The first RelatedWord should be created and because of the `after_create` in the RelatedWord model, the inverse of that should also be created.
And then the validation should stop the second one from being created again in the database.

**Comment by bigfishh** [comment]
ohh gotcha! that makes sense 🙂

**Pull request merged**
